<?php

// Translation of file /home/dennis/www/mandlen/modules/image/model.image.inc

$_COS_LANG_MODULE['image_add_image'] = 'Tilføj Billede';
$_COS_LANG_MODULE['image_form_abstract'] = 'Beskrivelse';
$_COS_LANG_MODULE['image_form_image'] = 'Vælg billede';
$_COS_LANG_MODULE['image_delete_label'] = 'Slet billede';
$_COS_LANG_MODULE['image_edit_label'] = 'Ret billede';
$_COS_LANG_MODULE['image_add_label'] = 'Tilføj billede';
$_COS_LANG_MODULE['image_no_file_specified'] = 'Ingen fil valgt';
$_COS_LANG_MODULE['image_file_too_big'] = 'Filen er for stor';
$_COS_LANG_MODULE['image_attached'] = 'Tilføj billede';
$_COS_LANG_MODULE['image_add'] = 'Tilføj';
$_COS_LANG_MODULE['image_download'] = 'Vis';
$_COS_LANG_MODULE['image_file_added'] = 'Indsæt billede';
$_COS_LANG_MODULE['image_file_deleted'] = 'Billede slettet';
$_COS_LANG_MODULE['image_file_edited'] = 'Billede rettet';
$_COS_LANG_MODULE['image_delete_image'] = 'Slet billede';
$_COS_LANG_MODULE['image_edit_image'] = 'Ret billede';

$_COS_LANG_MODULE['image_abstract_label'] = 'Abstrakt';
$_COS_LANG_MODULE['image_file_label'] = 'Vælg Billede Fil';
