<?php

$_COS_LANG_MODULE['Delete image'] = '删除图像';
$_COS_LANG_MODULE['Delete all images'] = '删除所有图像';
$_COS_LANG_MODULE['Edit image'] = '编辑图像';
$_COS_LANG_MODULE['Add image'] = '添加图片';
$_COS_LANG_MODULE['Abstract'] = '摘要';
$_COS_LANG_MODULE['Image width in pixels, e.g. 100'] = '以像素为单位的图像宽度，如100';
$_COS_LANG_MODULE['No file was specified'] = '没有指定的文件';
$_COS_LANG_MODULE['Edit images'] = '编辑图像';
$_COS_LANG_MODULE['Download'] = '下载';
$_COS_LANG_MODULE['Image was added'] = '添加图片';
$_COS_LANG_MODULE['Image was deleted'] = '图像中删除';
$_COS_LANG_MODULE['All images has been deleted'] = '所有图像已被删除';
$_COS_LANG_MODULE['Image was updated'] = '图片编辑';
