<?php


// Translation of file /modules/image/module.php

$_COS_LANG_MODULE['Add image'] = 'Add image';
$_COS_LANG_MODULE['Delete image'] = 'Delete image';
$_COS_LANG_MODULE['Delete all images'] = 'Delete all images';
$_COS_LANG_MODULE['Edit image'] = 'Edit image';
$_COS_LANG_MODULE['Image was added'] = 'Image added';
$_COS_LANG_MODULE['Images'] = 'Images';
$_COS_LANG_MODULE['Image deleted'] = 'Image deleted';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Abstract'] = 'Abstract';
$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['Add'] = 'Add';
$_COS_LANG_MODULE['Image width in pixels, e.g. 100'] = 'Image width in pixels, e.g. 100';
$_COS_LANG_MODULE['No file was specified'] = 'No file was specified';
$_COS_LANG_MODULE['Edit images'] = 'Edit images';
$_COS_LANG_MODULE['Download'] = 'Download';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Image was deleted'] = 'Image deleted';
$_COS_LANG_MODULE['All images has been deleted'] = 'All images has been deleted';
$_COS_LANG_MODULE['Image was updated'] = 'Image edited';
$_COS_LANG_MODULE['Access denied'] = 'Access denied';
