<?php

// Translation of Image /home/dennis/www/osnet/modules/image/delete.php

$_COS_LANG_MODULE['Edit image'] = 'Edit image';
// Translation of Image /home/dennis/www/osnet/modules/image/add.php

$_COS_LANG_MODULE['Add image'] = 'Add image';
// Translation of Image /home/dennis/www/osnet/modules/image/model.image.inc

$_COS_LANG_MODULE['Delete image'] = 'Delete image';

$_COS_LANG_MODULE['Edit image'] = 'Edit image';
$_COS_LANG_MODULE['Delete image'] = 'Delete image';
$_COS_LANG_MODULE['Add image'] = 'Add image';


$_COS_LANG_MODULE['image_form_abstract'] = 'Abstract';
$_COS_LANG_MODULE['image_form_image'] = 'Select image';


$_COS_LANG_MODULE['Download'] = 'Download';

$_COS_LANG_MODULE['Image was added'] = 'Image added';
$_COS_LANG_MODULE['Image was deleted'] = 'Image deleted';
$_COS_LANG_MODULE['Image was updated'] = 'Image edited';
// Translation of Image /home/dennis/www/osnet/modules/image/edit.php

$_COS_LANG_MODULE['Abstract'] = 'Abstract';


$_COS_LANG_MODULE['Delete all images'] = 'Delete all';
$_COS_LANG_MODULE['No file was specified'] = 'No file was specified';
$_COS_LANG_MODULE['All images has been deleted'] = 'All images has been deleted';
$_COS_LANG_MODULE['Delete all images'] = 'Delete all images';

$_COS_LANG_MODULE['Image width in pixels, e.g. 100'] = 'Image width in pixels, e.g. 100';
