<?php

// Translation of Image /home/dennis/www/osnet/modules/image/delete.php

$_COS_LANG_MODULE['image_edit_image'] = 'Edit Image';
// Translation of Image /home/dennis/www/osnet/modules/image/add.php

$_COS_LANG_MODULE['image_add_image'] = 'Add Image';
// Translation of Image /home/dennis/www/osnet/modules/image/model.image.inc

$_COS_LANG_MODULE['image_delete_image'] = 'Delete Image';

$_COS_LANG_MODULE['image_edit_label'] = 'Edit Image';
$_COS_LANG_MODULE['image_delete_label'] = 'Delete Image';
$_COS_LANG_MODULE['image_add_label'] = 'Add Image';

$_COS_LANG_MODULE['image_edit'] = 'Edit';
$_COS_LANG_MODULE['image_delete'] = 'Delete';
$_COS_LANG_MODULE['image_add'] = 'Add New Image';

$_COS_LANG_MODULE['image_form_abstract'] = 'Abstract';
$_COS_LANG_MODULE['image_form_image'] = 'Select Image';
$_COS_LANG_MODULE['image_delete_caption'] = 'Delete Image';
$_COS_LANG_MODULE['image_edit_caption'] = 'Edit Image';
$_COS_LANG_MODULE['image_add_caption'] = 'Add New Image';
$_COS_LANG_MODULE['image_no_image_specified'] = 'No Image Specified';
$_COS_LANG_MODULE['image_file_too_big'] = 'Image is to big';

$_COS_LANG_MODULE['image_attached'] = 'Image';
$_COS_LANG_MODULE['image_download'] = 'Download';

$_COS_LANG_MODULE['image_add_new'] = 'Add New';
$_COS_LANG_MODULE['image_add_image'] = 'Add New Image';
$_COS_LANG_MODULE['image_file_added'] = 'Image Added';
$_COS_LANG_MODULE['image_file_deleted'] = 'Image Deleted';
$_COS_LANG_MODULE['image_file_edited'] = 'Image Edited';
// Translation of Image /home/dennis/www/osnet/modules/image/edit.php

$_COS_LANG_MODULE['image_abstract_label'] = 'Abstract';
$_COS_LANG_MODULE['image_file_label'] = 'Choose Image File';

