<?php

$_COS_LANG_MODULE['Delete image'] = 'Slett denne Bilde';
$_COS_LANG_MODULE['Add image'] = 'Legg bilde';
$_COS_LANG_MODULE['Delete all images'] = 'Slette alle bilder';
$_COS_LANG_MODULE['Edit image'] = 'Rediger bilde';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['Image width in pixels, e.g. 100'] = 'Bredde i px (f.eks 100).';
$_COS_LANG_MODULE['No file was specified'] = 'Ingen fil valgt';
$_COS_LANG_MODULE['Edit images'] = 'Redigere bilder';
$_COS_LANG_MODULE['Download'] = 'Vis';
$_COS_LANG_MODULE['Image was added'] = 'Bilde lagt til';
$_COS_LANG_MODULE['Image was deleted'] = 'Bilde slettet';
$_COS_LANG_MODULE['All images has been deleted'] = 'Alle bildene slettes';
$_COS_LANG_MODULE['Image was updated'] = 'Bilde rettet';
