<?php

$_COS_LANG_MODULE['Delete image'] = 'Bild löschen';
$_COS_LANG_MODULE['Edit image'] = 'Bild bearbeiten';
$_COS_LANG_MODULE['Add image'] = 'Bild hinzufügen';
$_COS_LANG_MODULE['Delete all images'] = 'Alle Bilder löschen';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['Image width in pixels, e.g. 100'] = 'Bildbreite in Pixel, z. B. 100';
$_COS_LANG_MODULE['No file was specified'] = 'Keine Datei angegeben wurde';
$_COS_LANG_MODULE['Edit images'] = 'Bilder bearbeiten';
$_COS_LANG_MODULE['Download'] = 'Herunterladen';
$_COS_LANG_MODULE['Image was added'] = 'Bild hinzugefügt';
$_COS_LANG_MODULE['Image was deleted'] = 'Bild gelöscht';
$_COS_LANG_MODULE['All images has been deleted'] = 'Alle Bilder wurde gelöscht';
$_COS_LANG_MODULE['Image was updated'] = 'Bild bearbeitet';
