<?php

$_COS_LANG_MODULE['Edit image'] = 'Rediger billede';
$_COS_LANG_MODULE['Add image'] = 'Tilføj billede';
$_COS_LANG_MODULE['Delete image'] = 'Slet billede';
$_COS_LANG_MODULE['Edit images'] = 'Redigere billeder';
$_COS_LANG_MODULE['image_form_abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['image_form_image'] = 'Vælg billede';
$_COS_LANG_MODULE['Download'] = 'Hent';
$_COS_LANG_MODULE['Image was added'] = 'Billede tilføjet';
$_COS_LANG_MODULE['Image was deleted'] = 'Billede slettet';
$_COS_LANG_MODULE['Image was updated'] = 'Billede redigeret';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['Delete all images'] = 'Slet alle billeder';
$_COS_LANG_MODULE['No file was specified'] = 'Ingen fil blev angivet';
$_COS_LANG_MODULE['All images has been deleted'] = 'Alle billeder er blevet slettet';
$_COS_LANG_MODULE['Image width in pixels, e.g. 100'] = 'Billede bredde i pixels, fx 100';
