<?php

$_COS_LANG_MODULE['Delete image'] = 'Poista tämä kuva';
$_COS_LANG_MODULE['Delete all images'] = 'Poista kaikki kuvat';
$_COS_LANG_MODULE['Edit image'] = 'Muokkaa kuvaa';
$_COS_LANG_MODULE['Add image'] = 'Lisää kuva';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakti';
$_COS_LANG_MODULE['Image width in pixels, e.g. 100'] = 'Leveys px (esim. 100).';
$_COS_LANG_MODULE['No file was specified'] = 'Tiedostoa ei valittu';
$_COS_LANG_MODULE['Edit images'] = 'Edit Kuvat';
$_COS_LANG_MODULE['Download'] = 'Näyttää';
$_COS_LANG_MODULE['Image was added'] = 'Kuva lisätty';
$_COS_LANG_MODULE['Image was deleted'] = 'Kuva poistetaan';
$_COS_LANG_MODULE['All images has been deleted'] = 'Kaikki kuvat poistetaan';
$_COS_LANG_MODULE['Image was updated'] = 'Kuva suunnattu';
