<?php

$_COS_LANG_MODULE['Delete image'] = 'Radera bild';
$_COS_LANG_MODULE['Delete all images'] = 'Radera alla bilder';
$_COS_LANG_MODULE['Edit image'] = 'Redigera bild';
$_COS_LANG_MODULE['Add image'] = 'Add avbildar';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['Image width in pixels, e.g. 100'] = 'Bild bredd i pixlar, t.ex. 100';
$_COS_LANG_MODULE['No file was specified'] = 'Ingen fil angavs';
$_COS_LANG_MODULE['Edit images'] = 'Redigera bilder';
$_COS_LANG_MODULE['Download'] = 'Ladda ner';
$_COS_LANG_MODULE['Image was added'] = 'Bild tillsattes';
$_COS_LANG_MODULE['Image was deleted'] = 'Bild utgår';
$_COS_LANG_MODULE['All images has been deleted'] = 'Alla bilder har tagits bort';
$_COS_LANG_MODULE['Image was updated'] = 'Bild redigeras';
